### ISSUE TITLE
Verify why user agent is using uk instead of en

### ISSUE THREAD

**Issue by kober32** [wultra/networking-android#39]
As seen here:

https://github.com/wultra/lime-java-core/pull/224/files#diff-b547e02658cb0913fd2f5831a2819bb006777ad614c48c9857414a44963dbf4cR36

`"PowerAuthNetworking/1.2.1 (uk; wifi) com.wultra.android.mtoken.gdnexttest/1.0.0-gdnexttest (samsung; Android/13; SM-A047F)"`

**Comment by Hopsaheysa** [comment]
It is probably because gdnext is a Ukrainian company. So we get uk as a language.
